Automatic assistant creation
daveshap/OpenAI_Agent_Swarm pull request #168
Opened 2023-11-20 00:56 UTC by guillermo-delrio

- Assistants are automatically created if an ID is not found
- Removed the thread used to check for pending actions, now all is handled on a single thread per agent

2023-11-21 14:03 UTC, samgriek commented on agents/manual_assistants/README.md
> +# If you alredy had the openai module installed you may need to:
```suggestion
# If you already had the openai module installed you may need to:
```

2023-11-21 14:16 UTC, samgriek approved these changes
This is my first time going through a PR on this project so I'm not sure if you want a second review.  I didn't see anything obvious that would cause an issue.  There was one typo in the README.md for which I suggested a change.

2023-11-21 14:28 UTC, thehunmonkgroup requested changes

2023-11-21 14:28 UTC, thehunmonkgroup commented on agents/manual_assistants/OAIWrapper.py
> +            toolClass=globals().get(tool, None)
What's going on there? Seems an odd mechanism to be pulling a tool class.

2023-11-21 14:28 UTC, thehunmonkgroup commented on agents/manual_assistants/agentProcessor.py
> +        print("")
This may be scope creep, but I think a proper use of the Python logging module would be better instead of all these `print()` statements.

2023-11-21 14:28 UTC, thehunmonkgroup commented on agents/manual_assistants/agentTools/__init__.py
> +from .resolveTask import execute
This seems wrong, I don't think any of the earlier imports will be available, as the last import will overwrite the execute variable of all the previous.

2023-11-21 14:28 UTC, thehunmonkgroup commented on agents/manual_assistants/agentTools/assignTask.py
> +    }
Noting for later: I think a MUCH cleaner way to implement function definitions is to infer the tool description from the function and function documentation itself. I already have robust code that does this, and can share if you like.

2023-11-21 18:21 UTC, guillermo-delrio commented on agents/manual_assistants/OAIWrapper.py
> +            toolClass=globals().get(tool, None)
It is a weird syntax, it took me a while to get it working, but it's getting the tool class from the global context with the intend of then getting the tool definition and building the tool list that the API requires. I'm not sure how to approach this differently, but if you have code suggestions let me know.

2023-11-21 18:23 UTC, guillermo-delrio commented on agents/manual_assistants/agentProcessor.py
> +        print("")
That sounds great, maybe we can start a roadmap with these ideas? I usually like to make PRs that change only one thing (or as few as possible) so ti's easier to review

2023-11-21 18:33 UTC, guillermo-delrio commented on agents/manual_assistants/agentTools/__init__.py
> +from .resolveTask import execute
Somehow it was working well. I don't really understand why, but you're right that looks terrible. I've updated it. Thank you!

2023-11-21 18:34 UTC, guillermo-delrio commented on agents/manual_assistants/agentTools/assignTask.py
> +    }
Yes, that would be lovely. I think this is similar to the logging comment. Let's create a roadmap document and we can add these suggestions there so we can tackle them in future PRs.

2023-11-22 21:25 UTC, thehunmonkgroup approved these changes

2023-11-23 10:27 UTC, merged